### ISSUE TITLE
Update the docker-compose configuration file to reduce the container log file size

### ISSUE THREAD

**Issue by sumandari** [kartoza/projecta#1369]
We experienced disk space issues.
There was a large log file for nginx in 
11.3 GiB [##########] f72dd44c2ba3386523881cdb279f419f0de5e797c8b43fef1268505c97e9e121-json.log

Reduce the container log to avoid running out of disk space:
https://sleeplessbeastie.eu/2020/09/16/how-to-reduce-the-size-of-the-docker-container-log-file/

try to add this logging option in docker-compose:
```
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
```
